# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Npm Publish Package

env:
  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run build
      - name: Publish NPM
        if: '!github.event.release.prerelease'
        run: npm publish
      - name: Publish NPM (beta)
        if: 'github.event.release.prerelease'
        run: npm publish --tag beta
